package cz.heller.core.categorize

/**
 * Přednastavená pravidla obchodník → kategorie. Klíče jsou **normalizované**
 * (malá písmena, bez diakritiky) a porovnávají se metodou „normalizovaný text obsahuje klíč".
 * Matcher zkouší nejdelší (nejspecifičtější) klíče první. CZ/PL/MNE zaměřené (odladěno na reálných
 * Fio datech — ~95 % transakcí zařazeno automaticky), uživatelská naučená pravidla mají přednost.
 * Pozn.: klíče s koncovou mezerou („dpp ", „obi ", „google ") cílí na začátek tokenu.
 */
object SeedRules {

    val rules: List<Pair<String, String>> = listOf(
        // --- Potraviny ---
        "albert" to "food_groceries",
        "zabka" to "food_groceries",
        "biedronka" to "food_groceries",
        "kaufland" to "food_groceries",
        "billa" to "food_groceries",
        "tesco" to "food_groceries",
        "lidl" to "food_groceries",
        "penny" to "food_groceries",
        "globus" to "food_groceries",
        "makro" to "food_groceries",
        "spar" to "food_groceries",
        "potraviny" to "food_groceries",
        "minimarket" to "food_groceries",
        "vecerka" to "food_groceries",
        "carrefour" to "food_groceries",
        "auchan" to "food_groceries",
        "stokrotka" to "food_groceries",
        "dino w" to "food_groceries",
        "wtc company" to "food_groceries",
        "mega 4 kasa" to "food_groceries",
        "kantun" to "food_groceries",
        "idea kotor" to "food_groceries",
        // --- Restaurace, fast-food ---
        "mcdonald" to "food_restaurant",
        "kfc" to "food_restaurant",
        "burger" to "food_restaurant",
        "kebab" to "food_restaurant",
        "pizza" to "food_restaurant",
        "bageterie" to "food_restaurant",
        "subway" to "food_restaurant",
        "sushi" to "food_restaurant",
        "pasibus" to "food_restaurant",
        "restaurace" to "food_restaurant",
        "restaurant" to "food_restaurant",
        "restoran" to "food_restaurant",
        "restauracja" to "food_restaurant",
        "bistro" to "food_restaurant",
        "snack" to "food_restaurant",
        "gastronomi" to "food_restaurant",
        "karczma" to "food_restaurant",
        "bufet" to "food_restaurant",
        "vietthai" to "food_restaurant",
        "grill" to "food_restaurant",
        "kuchnia" to "food_restaurant",
        "jadlo" to "food_restaurant",
        "gastro west" to "food_restaurant",
        "little bay" to "food_restaurant",
        "flying bistro" to "food_restaurant",
        "bezrucova chata" to "food_restaurant",
        "tramontana" to "food_restaurant",
        "stari grad" to "food_restaurant",
        "sailor cattaro" to "food_restaurant",
        "krstac" to "food_restaurant",
        "dvor" to "food_restaurant",
        "nevjesta" to "food_restaurant",
        "callett" to "food_restaurant",
        "hasib" to "food_restaurant",
        "foodmania" to "food_restaurant",
        "makalu" to "food_restaurant",
        // --- Bar, kavárna ---
        "cafe" to "food_bar",
        "kavarna" to "food_bar",
        "coffee" to "food_bar",
        "kafe" to "food_bar",
        "kaficko" to "food_bar",
        "starbucks" to "food_bar",
        "sbx" to "food_bar",
        "cukiernia" to "food_bar",
        "lodziarnie" to "food_bar",
        "lody" to "food_bar",
        "zmrzlina" to "food_bar",
        "cokafe" to "food_bar",
        "espresso" to "food_bar",
        "shothouse" to "food_bar",
        "tobacco" to "food_bar",
        "pub" to "food_bar",
        "bakery" to "food_bar",
        "patisserie" to "food_bar",
        "kawiarnia" to "food_bar",
        "piekarnia" to "food_bar",
        "croissant" to "food_bar",
        "grycan" to "food_bar",
        "aroma 1" to "food_bar",
        "the spot" to "food_bar",
        "small talks" to "food_bar",
        "radioklub" to "food_bar",
        "impact hub" to "food_bar",
        "karlinska holka" to "food_bar",
        "moje misto" to "food_bar",
        "krizovatka" to "food_bar",
        // --- Palivo ---
        "shell" to "vehicle_fuel",
        "orlen" to "vehicle_fuel",
        "omv" to "vehicle_fuel",
        "benzina" to "vehicle_fuel",
        "eurooil" to "vehicle_fuel",
        "mol sf" to "vehicle_fuel",
        "jugopetrol" to "vehicle_fuel",
        "stacja" to "vehicle_fuel",
        // --- Parkování ---
        "parkum" to "vehicle_parking",
        "parking" to "vehicle_parking",
        "parkovani" to "vehicle_parking",
        "park ra" to "vehicle_parking",
        "brzeczkowice" to "vehicle_parking",
        "balice manual" to "vehicle_parking",
        "ap 1234" to "vehicle_parking",
        // --- Vozidlo: údržba / půjčovna ---
        "auto toman" to "vehicle_maintenance",
        "autotoman" to "vehicle_maintenance",
        "discovercars" to "vehicle_rental",
        // --- Veřejná doprava ---
        "kodis" to "transport_public",
        "csad" to "transport_public",
        "dpp " to "transport_public",
        "dpmo" to "transport_public",
        "dpmb" to "transport_public",
        "urbancard" to "transport_public",
        "bilety" to "transport_public",
        "jizdenka" to "transport_public",
        "dolazni terminal" to "transport_public",
        // --- Dálková doprava ---
        "flix" to "transport_long_distance",
        "regiojet" to "transport_long_distance",
        "cd cz" to "transport_long_distance",
        "ceske drahy" to "transport_long_distance",
        "koleo" to "transport_long_distance",
        "leo express" to "transport_long_distance",
        "student agency" to "transport_long_distance",
        // --- Taxi ---
        "bolt" to "transport_taxi",
        "uber" to "transport_taxi",
        "liftago" to "transport_taxi",
        // --- Dovolená, hotely ---
        "booking" to "life_holidays",
        "hotel" to "life_holidays",
        "hostel" to "life_holidays",
        "airbnb" to "life_holidays",
        "apartman" to "life_holidays",
        "penzion" to "life_holidays",
        "monte put" to "life_holidays",
        "soa budva" to "life_holidays",
        // --- Telefon ---
        "t mobile" to "comm_phone",
        "vodafone" to "comm_phone",
        // --- Software, aplikace (osobní) ---
        "apple com" to "comm_software",
        "google chrome" to "comm_software",
        "microsoft" to "comm_software",
        "playstation" to "comm_software",
        "steam" to "comm_software",
        "icloud" to "comm_software",
        "higgsfield" to "comm_software",
        // --- Práce / Podnikání (dev/AI nástroje) ---
        "anthropic" to "work",
        "claude" to "work",
        "openai" to "work",
        "chatgpt" to "work",
        "vercel" to "work",
        "supabase" to "work",
        "firecrawl" to "work",
        "github" to "work",
        "google cloud" to "work",
        "idoklad" to "work",
        "cloudflare" to "work",
        "openrouter" to "work",
        "entyai" to "work",
        "google " to "work",
        // --- Televize, streaming ---
        "netflix" to "life_tv",
        "spotify" to "life_tv",
        "hbo" to "life_tv",
        "disney" to "life_tv",
        // ČT/ČRo poplatek je povinný → Daně (na přání uživatele, ne „Televize").
        "ceska televize" to "financial_taxes",
        "vypalne ceska" to "financial_taxes",
        // --- Elektronika ---
        "alza" to "shopping_electronics",
        "planeo" to "shopping_electronics",
        "datart" to "shopping_electronics",
        "mironet" to "shopping_electronics",
        "media markt" to "shopping_electronics",
        "mediamarkt" to "shopping_electronics",
        // --- Domácnost, zahrada ---
        "ikea" to "shopping_home_garden",
        "obi " to "shopping_home_garden",
        "hornbach" to "shopping_home_garden",
        "bauhaus" to "shopping_home_garden",
        "jysk" to "shopping_home_garden",
        "mountfield" to "shopping_home_garden",
        "castorama" to "shopping_home_garden",
        "leroy merlin" to "shopping_home_garden",
        // --- Oděvy a obuv ---
        "tk maxx" to "shopping_clothes",
        "zara" to "shopping_clothes",
        "deichmann" to "shopping_clothes",
        "reserved" to "shopping_clothes",
        "sinsay" to "shopping_clothes",
        "primark" to "shopping_clothes",
        "zalando" to "shopping_clothes",
        // --- Sport, fitness ---
        "decathlon" to "life_sport",
        "form factory" to "life_sport",
        "fitness" to "life_sport",
        "sportisimo" to "life_sport",
        // --- Drogerie ---
        "rossmann" to "shopping_drugstore",
        "dm drogerie" to "shopping_drugstore",
        "teta" to "shopping_drugstore",
        "drogerie" to "shopping_drugstore",
        "notino" to "shopping_drugstore",
        // --- Zdravotní péče, lékárna ---
        "apteka" to "life_healthcare",
        "lekarna" to "life_healthcare",
        "pharmacy" to "life_healthcare",
        "benu" to "life_healthcare",
        "dr max" to "life_healthcare",
        "zubni" to "life_healthcare",
        "poliklinika" to "life_healthcare",
        "nemocnice" to "life_healthcare",
        "medicine" to "life_healthcare",
        // --- Pojištění (typy dříve než obecné) ---
        "auto pojisteni" to "vehicle_vehicle_insurance",
        "povinne ruceni" to "vehicle_vehicle_insurance",
        "havarijni" to "vehicle_vehicle_insurance",
        "zivotni pojisteni" to "financial_insurance",
        "kooperativa" to "financial_insurance",
        "generali" to "financial_insurance",
        "allianz" to "financial_insurance",
        "pojistovna" to "financial_insurance",
        "koop cz" to "financial_insurance",
        // --- Energie, komunál ---
        "cez" to "housing_utilities",
        "e on" to "housing_utilities",
        "innogy" to "housing_utilities",
        "elektrina" to "housing_utilities",
        "platba ele" to "housing_utilities",
        "odpady" to "housing_utilities",
        "vodarny" to "housing_utilities",
        "teplarny" to "housing_utilities",
        // --- Bydlení, služby ---
        "byt sluzby" to "housing_services",
        "spolecenstvi vlastniku" to "housing_services",
        "nedoplatek vyuctovani" to "housing_services",
        // --- Hypotéka ---
        "splatka hu" to "housing_mortgage",
        "hypoteka" to "housing_mortgage",
        "hyposporici" to "housing_mortgage",
        // --- Půjčky, splátky ---
        "zonky" to "financial_loans",
        "cetelem" to "financial_loans",
        "home credit" to "financial_loans",
        "cofidis" to "financial_loans",
        "provident" to "financial_loans",
        // --- Pokuty ---
        "pokuty" to "financial_fines",
        "pokuta" to "financial_fines",
        "usekove mereni" to "financial_fines",
        // --- Výběr hotovosti z bankomatu ---
        "bankomat" to "cash_withdrawal",
        // --- Poplatky / úřady ---
        "magistrat" to "financial_fees",
        "mmhs" to "financial_fees",
        // --- Charita, dary ---
        "darujme" to "life_charity",
        "charita" to "life_charity",
        "nadace" to "life_charity",
        "clovek v tisni" to "life_charity",
        "dar esk" to "life_charity",
        "splozene dite" to "life_charity",
        // --- Investice ---
        "trading 212" to "investments_financial",
        "trading212" to "investments_financial",
        "frostember" to "investments_financial",
        "portu" to "investments_financial",
        "fondee" to "investments_financial",
        "degiro" to "investments_financial",
        "etoro" to "investments_financial",
        // --- Kultura, vstupenky ---
        "smsticket" to "life_culture",
        "vstupenky" to "life_culture",
        "kino" to "life_culture",
        "cinestar" to "life_culture",
        "divadlo" to "life_culture",
        "muzeum" to "life_culture",
        "mauzolej" to "life_culture",
        "bumbum comedy" to "life_culture",
        "galerie" to "life_culture",
        // --- Dárky, suvenýry ---
        "suvenir" to "shopping_gifts",
        "pamia" to "shopping_gifts",
        // --- Obchodní centra / tržiště (volný čas) ---
        "futurum" to "shopping_free_time",
        "avion" to "shopping_free_time",
        "temu" to "shopping_free_time",
        "allegro" to "shopping_free_time",
        "aliexpress" to "shopping_free_time",
        // --- Holičství, kadeřnictví, kosmetika (wellness, krása) ---
        "barber" to "life_wellness",
        "kadernic" to "life_wellness",
        "holicstvi" to "life_wellness",
        "frizer" to "life_wellness",
        "kosmeticky salon" to "life_wellness",
        "manikura" to "life_wellness",
        // --- Zdravotní a sociální pojištění, daně → Daně (povinné odvody) ---
        // Pozn.: „zdravotní pojišťovna/pojištění" má přednost před obecnou „pojistovna" (delší klíč).
        "zdravotni pojist" to "financial_taxes",
        "revirni bratrska" to "financial_taxes",
        "socialniho zabezpeceni" to "financial_taxes",
        "socialni zabezpeceni" to "financial_taxes",
        "socialni pojisteni" to "financial_taxes",
        "socialni osvc" to "financial_taxes",
        "zdravotni osvc" to "financial_taxes",
        "financni urad" to "financial_taxes",
        "zalohy fu" to "financial_taxes",
        "rbp" to "financial_taxes",
        "vzp" to "financial_taxes",
        "ossz" to "financial_taxes",
        "cssz" to "financial_taxes",
    )

    /** Nejdelší (nejspecifičtější) klíče první, ať „auto pojisteni" vyhraje nad „pojistovna". */
    val sorted: List<Pair<String, String>> = rules.sortedByDescending { it.first.length }
}
